if(!self.define){let e,s={};const n=(n,c)=>(n=new URL(n+".js",c).href,s[n]||new Promise(s=>{if("document"in self){const e=document.createElement("script");e.src=n,e.onload=s,document.head.appendChild(e)}else e=n,importScripts(n),s()}).then(()=>{let e=s[n];if(!e)throw new Error(`Module ${n} didn’t register its module`);return e}));self.define=(c,i)=>{const o=e||("document"in self?document.currentScript.src:"")||location.href;if(s[o])return;let t={};const a=e=>n(e,o),r={module:{uri:o},exports:t,require:a};s[o]=Promise.all(c.map(e=>r[e]||a(e))).then(e=>(i(...e),t))}}define(["./workbox-422b2006"],function(e){"use strict";self.skipWaiting(),e.clientsClaim(),e.precacheAndRoute([{url:"workbook-config.js",revision:"ded5c66854aa07733c54562723fb576b"},{url:"package.json",revision:"7d4387312834f795729cd72565d45b10"},{url:"package-lock.json",revision:"73473c1353d7004aab2e515167837981"},{url:"manifest.json",revision:"db567c02e62d92438e6aaa4b9377e6ac"},{url:"index.html",revision:"a015d2e39a10b6e545a6aaa4d247fc88"},{url:"capacitor-config.json",revision:"c52eaf1120583b00f82c42c7484764b6"},{url:"app.js",revision:"4c7d0f8ab39488e8ed92e3ded0029d8c"}],{}),e.cleanupOutdatedCaches(),e.registerRoute(/^https:\/\/cdn\.jsdelivr\.net\/.*/i,new e.CacheFirst({cacheName:"cdn-assets",plugins:[new e.ExpirationPlugin({maxEntries:80,maxAgeSeconds:2592e3}),new e.CacheableResponsePlugin({statuses:[0,200]})]}),"GET"),e.registerRoute(/^https:\/\/cdnjs\.cloudflare\.com\/.*/i,new e.CacheFirst({cacheName:"cdnjs-assets",plugins:[new e.ExpirationPlugin({maxEntries:40,maxAgeSeconds:2592e3}),new e.CacheableResponsePlugin({statuses:[0,200]})]}),"GET"),e.registerRoute(/^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,new e.StaleWhileRevalidate({cacheName:"font-assets",plugins:[new e.ExpirationPlugin({maxEntries:30,maxAgeSeconds:2592e3})]}),"GET")});

/* Code Studio Pro service-worker runtime hardening.
 * This block is intentionally dependency-free because sw.js is generated by Workbox.
 * It does not cache authenticated API responses. Workspace/auth data remains network-only.
 */
(() => {
  const RUNTIME_PAGE_CACHE = 'code-studio-pages-v1';

  self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'CODE_STUDIO_SKIP_WAITING') {
      self.skipWaiting();
    }
  });

  self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
      const keep = new Set([RUNTIME_PAGE_CACHE]);
      const names = await caches.keys();
      await Promise.all(names
        .filter((name) => name.startsWith('code-studio-pages-') && !keep.has(name))
        .map((name) => caches.delete(name)));
      await self.clients.claim();
    })());
  });

  self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (request.method !== 'GET' || request.mode !== 'navigate') return;

    const url = new URL(request.url);
    if (url.origin !== self.location.origin || url.pathname.startsWith('/api/') || url.pathname.startsWith('/v1/')) return;

    event.respondWith((async () => {
      try {
        const preload = event.preloadResponse ? await event.preloadResponse : null;
        const response = preload || await fetch(request);
        if (response && response.ok) {
          const cache = await caches.open(RUNTIME_PAGE_CACHE);
          await cache.put(request, response.clone());
        }
        return response;
      } catch {
        const cache = await caches.open(RUNTIME_PAGE_CACHE);
        const cached = await cache.match(request);
        if (cached) return cached;
        const shell = await caches.match('index.html');
        if (shell) return shell;
        return new Response('<!doctype html><title>Code Studio offline</title><p>Code Studio is offline. Reconnect and try again.</p>', {
          status: 503,
          headers: { 'Content-Type': 'text/html; charset=utf-8' }
        });
      }
    })());
  });
})();

